pip install python-dotenv
pip install jupyterlab
pip install ipywidgets
pip install requests
pip install numpy
pip install pandas
pip install scipy
pip install scikit-learn
pip install matplotlib
pip install gensim
pip install torch
pip install transformers
pip install tqdm
pip install openai
pip install gradio
pip install langchain
pip install tiktoken
pip install faiss-cpu
pip install langchain-openai
pip install langchain_experimental
pip install langchain_chroma
pip install langchain[docarray]
pip install datasets
pip install sentencepiece
pip install matplotlib
pip install google-generativeai
pip install anthropic
pip install scikit-learn
pip install unstructured
pip install chromadb
pip install plotly
pip install jupyter-dash
pip install beautifulsoup4
pip install pydub
pip install modal
pip install ollama
pip install accelerate
pip install sentencepiece
pip install bitsandbytes
pip install psutil
pip install setuptools
pip install speedtest-cli
pip install sentence_transformers
pip install feedparser
